spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/master?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password:
#    type: com.alibaba.druid.pool.DruidDataSource

#    initial-size: 10
#    max-active: 100
#    min-idle: 10
#    max-wait: 60000
#    pool-prepared-statements: true
#    max-pool-prepared-statement-per-connection-size: 20
#    time-between-eviction-runs-millis: 60000
#    min-evictable-idle-time-millis: 300000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mygod.project.entity
##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456